Make eznap pure bash and minor updates
- start versioning at 0.2.0
- use custom zprop with proper app ID (cz.jfi.eznap)
- change default frequent keep to 2 days worth (96)
- explain error codes in usage
- make $() statements more readable
- more readable logic on com.sun:auto-snapshot:<label> handling
- make all labels active by default:
  - to disable a label, you need to set it to "false" explicitly
-

diff --git a/bin/eznap b/bin/eznap
--- a/bin/eznap
+++ b/bin/eznap
@@ -1,9 +1,14 @@
 #!/usr/bin/env bash
 
-declare -A _keep
+appId="cz.jfi.eznap"
+appName="eznap"
+version="0.2.0"
 
+declare -A _keep
+## Default number of snapshots to keep for each label
+#
 _keep=(
-  [frequent]='4'
+  [frequent]='96'
   [hourly]='48'
   [daily]='14'
   [weekly]='8'
@@ -14,13 +19,14 @@ ret=0
 
 usage() {
   echo "Usage: $0 <$(printf '%s | ' ${!_keep[@]} | head -c -3)>"
+  echo "Retun codes: 0 - success"
+  echo "             1 - fatal failure, no changes made"
+  echo "             2 - partial failure, some changes possibly made"
 }
-
 
 err() {
   echo $* > /dev/stderr
 }
-
 
 failcode() {
   ret=$1
@@ -29,59 +35,84 @@ failcode() {
   exit $ret
 }
 
-
 fail() {
   failcode 1 $*
 }
 
+snapsToDestroy() {
+  readarray -tn 0 line
 
-_zfs=`which zfs &>/dev/null`
-[ $? -gt 0 ] && fail '`zfs` command not found.'
+  ## remove first $1 lines from output
+  ## that is, print all snapshots that should be destroyed
+  ## assuming they are sorted by date, oldest last
+  #
+  printf '%s\n' "${line[@]:$1}"
+}
 
-which tail &>/dev/null
-[ $? -gt 0 ] && fail '`tail` command not found.'
+_zfs=$(command -pv zfs 2> /dev/null)
+[[ $? -gt 0 ]] && fail '`zfs` command not found.'
 
+[[ -z "$1" ]] && fail "Missing label." `usage`
 
-[ -z $1 ] && fail "Syntax error." `usage`
-
-[ -z "${_keep[$1]}" ] && fail "Syntax error." `usage`
-
+[[ -z "${_keep[$1]}" ]] && fail "Wrong label." `usage`
 
 label=$1
 
-DATASETS=$(env LC_ALL=C zfs list -Ht filesystem,volume -o name,com.sun:auto-snapshot,com.sun:auto-snapshot:${label})
-[ $? -gt 0 ] && fail 'Error enumerating zfs datasets.'
+## -H makes the output script-friendly
+#
+DATASETS=$(
+  env LC_ALL=C \
+  $_zfs list -H \
+  -t filesystem,volume \
+  -o name,com.sun:auto-snapshot,com.sun:auto-snapshot:$label \
+  2>&1
+)
 
+[[ $? -gt 0 ]] && fail -e "Error enumerating zfs datasets. Command output:\n" "$DATASETS"
 
-while read name snap keep; do
-  if [ ${keep,,} = "true" ]; then keep=${_keep[$label]}; fi
+while read dataset snap keep; do
 
-  if [[ "${snap,,}" = "true" && "$keep" =~ ^[0-9]+$ ]]; then
-    if [ $keep -gt 0 ]; then
-      SNAPPROPS="-o eznap:label=$label"
-      SNAPNAME="$name@eznap-${label}_$(date -u +"%Y-%d-%m_%H:%M:%S")"
-      zfs snapshot $SNAPPROPS "$SNAPNAME" 2>/dev/null
-      [ $? -gt 0 ] && err "Create snapshot failed for '$SNAPNAME'." && ret=2
+  case "${keep,,}" in
+  ## '-' (not set) and 'true' means use default retention
+    "-" | "true")  keep=${_keep[$label]} ;;
+  ## anything else but a positive integer means no snapshot
+    '' | *[!0-9]*) snap=false ;;
+  esac
+
+  if [[ "${snap,,}" = "true" ]]; then
+
+    if [[ $keep -gt 0 ]]; then
+      _date=$(TZ=UTC printf '%(%F_%T)TZ')
+      SNAPPROPS="-o ${appId}:label=$label"
+      SNAPNAME="${dataset}@${appName}-${label}_${_date}"
+      $_zfs snapshot $SNAPPROPS "$SNAPNAME" 2>/dev/null
+      [[ $? -gt 0 ]] && err "Create snapshot failed for '$SNAPNAME'." && ret=2
     fi
 
-    SNAPSHOTS=$(env LC_ALL=C zfs list -H -t snapshot -S creation -o name,eznap:label)
-    [ $? -gt 0 ] && err "Error enumerating zfs snapshots. No old snapshots deleted for dataset '$name'." && ret=2
+    SNAPSHOTS=$(
+      env LC_ALL=C \
+      $_zfs list -H \
+      -t snapshot \
+      -S creation \
+      -o name,${appId}:label \
+      $dataset
+    )
+    [[ $? -gt 0 ]] && failcode 2 "Error enumerating zfs snapshots. No old snapshots deleted for dataset '${dataset}'."
 
     DESTROY=$(
       while read sname slabel; do
-        if [ "${sname%%@*}" = "$name" -a "$slabel" = "$label" ]; then
+        if [[ "${sname%%@*}" = "$dataset" && "$slabel" = "$label" ]]; then
           echo $sname
         fi
-      done <<< $SNAPSHOTS | tail -n +$(( $keep + 1 ))
+      done <<< $SNAPSHOTS | snapsToDestroy $keep
     )
 
     for sn in $DESTROY; do
-      zfs destroy "$sn" 2>/dev/null
-      [ $? -gt 0 ] && err "Destroy snapshot failed for '$sn'." && ret=2
+      $_zfs destroy "$sn" 2>/dev/null
+      [[ $? -gt 0 ]] && err "Destroy snapshot failed for '$sn'." && ret=2
     done
 
   fi
 done <<< $DATASETS
 
 exit $ret
-
